<a href="https://colab.research.google.com/github/a01286849-glitch/damian-garza-kosikova-A01286849/blob/main/A4_Pivot_tables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

ruta = "/content/drive/MyDrive/antropometria-dataset-2.csv"
datos = pd.read_csv(ruta)

display(datos.head())

,folio,intp,entidad,desc_ent,sexo,edad,meses,peso,ropa,talla,...,hpresion,tbrazo,htension,PrimaryLast,code_upm,est_dis,est_urb,est_marg,pondef,est_var
0,210295,2,21,PUEBLA,2,38,8,73.70,2,146.4,...,16:30,2,16:35,1,R2101,5,3,1,3470.002176,215
1,101655,3,10,DURANGO,2,11,11,35.65,2,145.1,...,15:25,3,15:25,1,M1041,1,1,1,417.946672,101
2,10287,6,1,AGUASCALIENTES,2,18,8,54.80,1,162.0,...,9:40,1,9:40,1,M0108,5,3,1,472.980811,15
3,91526,4,9,DISTRITO FEDERAL,1,10,8,33.40,2,146.5,...,7:40,3,7:45,1,M0931,4,3,2,1832.581391,94
4,210939,3,21,PUEBLA,2,19,3,97.95,2,161.0,...,6:00,2,6:00,1,M2123,5,3,1,7622.066564,215

In [2]:
tabla = pd.pivot_table(
    datos,
    index="desc_ent",
    values="peso",
    aggfunc="mean"
)

promedio_zacatecas = tabla.loc["ZACATECAS", "peso"]

print("Promedio exacto:", promedio_zacatecas)
print(f"Promedio con dos decimales: {promedio_zacatecas:.2f}")

Promedio exacto: 64.23852445193928
Promedio con dos decimales: 64.24

In [3]:
tabla_mediana = pd.pivot_table(
    datos,
    index="desc_ent",
    columns="sexo",
    values="peso",
    aggfunc="median"
)

display(tabla_mediana.loc[["YUCATAN"]])

print("Respuesta:", tabla_mediana.loc["YUCATAN", 1])

sexo         1       2
desc_ent
YUCATAN   66.0  59.575

Respuesta: 66.0

In [4]:
tabla_promedios = pd.pivot_table(
    datos,
    index="desc_ent",
    columns="sexo",
    values="peso",
    aggfunc="mean"
)

print("Estado:", tabla_promedios[2].idxmax())
print("Promedio máximo:", tabla_promedios[2].max())

Estado: BAJA CALIFORNIA SUR
Promedio máximo: 68.1689591078067

In [5]:
adult = pd.read_csv("/content/drive/MyDrive/adult.csv")

adult["education"] = adult["education"].str.strip()
adult["marital-status"] = adult["marital-status"].str.strip()

In [6]:
tabla_horas = pd.pivot_table(
    adult,
    index="education",
    columns="marital-status",
    values="hours-per-week",
    aggfunc="mean"
)

resultado = tabla_horas.loc["HS-grad", "Divorced"]

print("Promedio:", resultado)

Promedio: 40.668319900805955

In [7]:
for columna in ["sex", "marital-status", "education"]:
    adult[columna] = adult[columna].str.strip()

tabla_edad = pd.pivot_table(
    adult,
    index=["education", "marital-status"],
    columns="sex",
    values="age",
    aggfunc="median"
)

resultado = tabla_edad.loc[
    ("Bachelors", "Married-AF-spouse"), "Male"
]

print("Mediana de edad:", resultado)

Mediana de edad: 34.5